server:
  port: 8204
spring:
  application:
    name: payimp
  boot:
      admin:
        client:
          url: http://192.168.200.135:7000
  zipkin:
    base-url: http://192.168.200.135:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://192.168.200.85:6801/eureka/,http://192.168.200.135:6802/eureka/,http://192.168.200.136:6803/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
     env:
       enabled: true
feign:
  hystrix:
    enabled: true
